apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://charts.zitadel.com'
    chart: zitadel
    targetRevision: 9.13.0
    helm:
      values: |
        zitadel:
          masterkeySecretName: zitadel-masterkey
          configmapConfig:
            ExternalDomain: "identity.kurza.nl"
            ExternalPort: 443
            TLS:
              Enabled: false
            Database:
              Postgres:
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: "30m"
                MaxConnIdleTime: "5m"
                User:
                  SSL:
                    Mode: "disable"
                Admin:
                  SSL:
                    Mode: "disable"
        ingress:
          enabled: true
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
        login:
          ingress:
            enabled: true
            className: "traefik"
            annotations:
              cert-manager.io/cluster-issuer: "letsencrypt-prod"
          image:
            tag: "v4.7.0"
        image:
          tag: "v4.7.0"
        env:
          - name: ZITADEL_DATABASE_POSTGRES_HOST
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-app
                key: host
          - name: ZITADEL_DATABASE_POSTGRES_PORT
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-app
                key: port
          - name: ZITADEL_DATABASE_POSTGRES_DATABASE
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-app
                key: dbname
          - name: ZITADEL_DATABASE_POSTGRES_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-app
                key: password
          - name: ZITADEL_DATABASE_POSTGRES_USER_USERNAME
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-app
                key: user
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_PASSWORD
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-superuser
                key: password
          - name: ZITADEL_DATABASE_POSTGRES_ADMIN_USERNAME
            valueFrom:
              secretKeyRef:
                name: zitadel-postgres-cluster-superuser
                key: user
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: zitadel-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true