apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'ghcr.io/actions/actions-runner-controller-charts'
    chart: "gha-runner-scale-set-controller"
    targetRevision: 0.13.1
    helm:
      valuesObject:
        controllerServiceAccount:
          namespace: gha-arc-system
          name: gha-runner-scale-set-controller-gha-rs-controller
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gha-arc-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true