apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gha-runner-scale-set-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set'
    targetRevision: 0.13.1
    helm:
      valuesObject:
        githubConfigSecret: gha-arc-personal
        githubConfigUrl: "https://github.com/metmij"
        runnerScaleSetName: selfhosted
        maxRunners: 5
        minRunners: 0
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gha-arc-runners-personal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true