{{- $targetRevision := .Values.targetRevision -}}
{{ $controller := .Values.controller -}}

{{- range .Values.accounts}}
{{ $name := .name -}}
{{ $accountName := .accountName -}}
{{ $secretName := .secretName -}}
{{ $scaleSetName := .scaleSetName -}}
{{ $minRunners := .minRunners -}}
{{ $maxRunners := .maxRunners -}}
{{- range .repositories}}
{{ $repository := . -}}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: runner-scale-set-{{$name}}-{{$repository}}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  project: default
  source:
    repoURL: 'ghcr.io/actions/actions-runner-controller-charts'
    chart: "gha-runner-scale-set"
    targetRevision: {{$targetRevision}}
    helm:
      valuesObject:
        controllerServiceAccount:
          namespace: {{$controller.namespace}}
          name: {{$controller.name}}-gha-rs-controller
        template:
          spec:
            initContainers:
              - name: init-dind-externals
                image: kurza/gha-arc-runner:latest
                imagePullPolicy: Always
                command: [ "cp", "-r", "-v", "/home/runner/externals/.", "/home/runner/tmpDir/" ]
                volumeMounts:
                  - name: dind-externals
                    mountPath: /home/runner/tmpDir
            containers:
              - name: runner
                image: kurza/gha-arc-runner:latest
                imagePullPolicy: Always
                command: [ "/home/runner/run.sh" ]
                env:
                  - name: DOCKER_HOST
                    value: unix:///run/docker/docker.sock
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /run/docker
                    readOnly: true
              - name: dind
                image: docker:dind
                args:
                  - dockerd
                  - --host=unix:///run/docker/docker.sock
                  - --group=$(DOCKER_GROUP_GID)
                env:
                  - name: DOCKER_GROUP_GID
                    value: "123"
                securityContext:
                  privileged: true
                volumeMounts:
                  - name: work
                    mountPath: /home/runner/_work
                  - name: dind-sock
                    mountPath: /run/docker
                  - name: dind-externals
                    mountPath: /home/runner/externals
            volumes:
              - name: work
                emptyDir: { }
              - name: dind-sock
                emptyDir: { }
              - name: dind-externals
                emptyDir: { }
        githubConfigSecret: {{$secretName}}
        githubConfigUrl: "https://github.com/{{$accountName}}/{{$repository}}"
        maxRunners: {{$maxRunners}}
        minRunners: {{$minRunners}}
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gha-arc-runners-{{$name}}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
{{- end}}
{{- end}}